name: CI

on: [push, pull_request]

jobs:
  build:
    # Thiết lập môi trường chạy là Ubuntu
    runs-on: ubuntu-latest

    # Các bước trong job
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Cài đặt dependencies
      - name: Install dependencies
        run: npm install react-number-format --legacy-peer-deps

      # Kiểm tra code với ESLint
      - name: Lint code
        run: npm run lint

      # Build dự án
      - name: Build project
        run: npm run build

  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          sudo apt update
          sudo apt install -y sudo
          sudo apt install -y git curl
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits --legacy-peer-deps
          npm install commitlint --legacy-peer-deps

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
